global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Godot;
global using GDShrapt.Reader;
global using GDShrapt.Linter;
global using GDShrapt.Formatter;
global using GDShrapt.Semantics;
global using GDDiagnosticSeverity = GDShrapt.Semantics.GDDiagnosticSeverity;
global using GD = Godot.GD;
global using Environment = System.Environment;
