namespace GDShrapt.Reader
{
    public enum GDOperationType
    {
        Literal,
        ArrayInitializer,
        Brackets,
        Call,
        Identifier,
        Member,
        Parameters,
        Indexer,
        Return,
        Pass,
        MatchCaseVariable,
        DictionaryInitializer,
        GetUniqueNode,
        GetNode,
        NodePath,
        If,
        Continue,
        DefaultOperator,
        Breakpoint,
        Break,
        Yeild,
        Await,
        Method,
        Rest
    }
}
